name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.NEKOYUME_PAT_TOKEN }}
          release-type: simple

  build-and-release:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Update Android version
        run: |
          VERSION="${{ needs.release-please.outputs.version }}"
          VERSION_CODE=$(date +%s)

          # Update versionName and versionCode in build.gradle.kts
          sed -i "s/versionName = \".*\"/versionName = \"$VERSION\"/" app/build.gradle.kts
          sed -i "s/versionCode = [0-9]*/versionCode = $VERSION_CODE/" app/build.gradle.kts

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Sign APK
        id: sign_apk
        uses: ilharp/sign-android-release@v2
        with:
          releaseDir: app/build/outputs/apk/release
          signingKey: ${{ secrets.SIGNING_KEYSTORE }}
          keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          keyAlias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Rename APK with version
        run: |
          mv ${{ steps.sign_apk.outputs.signedFile }} nekoyume-${{ needs.release-please.outputs.version }}.apk

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.NEKOYUME_PAT_TOKEN }}
        run: |
          gh release upload ${{ needs.release-please.outputs.tag_name }} nekoyume-${{ needs.release-please.outputs.version }}.apk

      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          update_release_body: true
          files: |
            nekoyume-${{ needs.release-please.outputs.version }}.apk
