name: "VirusTotal Scan Release Assets"

permissions:
  # Required to read release assets and write to the GitHub Release body
  contents: write

on:
  workflow_run:
    workflows: [build-and-release]
    types: [completed]
  #release:
  #  types:
  #    - published

jobs:
  virustotal:
    runs-on: ubuntu-latest
    #if: github.event.workflow_run.conclusion == 'success'
    permissions:
      # Required for the crazy-max/ghaction-virustotal action to update the release body
      contents: write
    steps:
      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          update_release_body: true
          # The release-build.yml workflow creates an APK file, so we target .apk$
          files: |
            .apk$
